config/routes.rb
Rails.application.routes.draw do
  resources :events
  devise_for :users
  root "tasks#index"
  resources :tasks, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :mypage, only: [:index, :show]
  resources :events
  # root 'events#index'
end

app/models/action.rb
class Action < ApplicationRecord
  belongs_to :task, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :task, optional: true

end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :task, optional: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :task_tags, dependent: :destroy
end

app/models/target.rb
class Target < ApplicationRecord
  belongs_to :task, optional: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :task_tags, dependent: :destroy
  has_many :tags, through: :task_tags, dependent: :destroy
  has_one :place, through: :task
  has_one :person, through: :task
  has_one :target
  has_one :action, through: :task

  scope :completed, -> {
    where(:completed => true)
  }

  scope :todo, -> {
    where(:completed => false)
  }

  scope :today, -> {
    where("due_date BETWEEN ? AND ?", '2010-01-01 00:00:00', Time.now.end_of_day)
  }

  scope :thisweek, -> {
    where(due_date: Time.now.all_week)
  }

  scope :thismonth, -> {
    where(due_date: Time.now.all_month)
  }

end

app/models/task_tag.rb
class TaskTag < ApplicationRecord
  belongs_to :task, dependent: :destroy
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :name, presence: true, uniqueness: true

  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :description, :start_date, :end_date)
    end
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  def index
    @tasks = current_user.tasks.order('due_date')
    @finish_tasks = current_user.tasks.completed.order(completed_at: :desc)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = current_user.tasks.order('due_date')


    # if @tasks.complete == false
    @other_tasks = Task.where.not(user_id: current_user.id).order(completed_at: :desc).limit(3)
    @finish_tasks = current_user.tasks.completed.order(completed_at: :desc).limit(3)
  end

  def new
    @task = Task.new
  end

  def create
    # binding.pry
    Task.create(task_params)
  end

  def update
    task = Task.find(params[:id])
    if request.referrer.include?("edit")
      task.update(task_params)
    else
      task.update(completed: true , completed_at: Time.now)
      redirect_to tasks_path
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def destroy
    task = Task.find(params[:id])
    Task.find(params[:id]).tags.destroy_all
    task.destroy
  end

  private
  def task_params
    params.require(:task).permit(:id, :place_id, :person_id, :target_id, :action_id, :due_date, :memo, :completed, :completed_at, { :tag_ids=> [] }).merge(user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/events/_form.html.haml
= form_with(model: @event, local: true) do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :start_date
    = f.datetime_select :start_date
  .field
    = f.label :end_date
    = f.datetime_select :end_date
  .actions
    = f.submit 'Save'

app/views/events/edit.html.haml
%h1 Editing event

= render 'form'

= link_to 'Show', @event
\|
= link_to 'Back', events_path

app/views/events/index.html.haml
= stylesheet_link_tag "/assets/fullcalendar.css"
= javascript_include_tag "https://momentjs.com/downloads/moment.js"
= javascript_include_tag "/assets/fullcalendar.js"
= javascript_include_tag "/assets/locale-all.js"
= javascript_include_tag "/assets/calendar.js"


%h1 Listing events

%table
  %thead
    %tr
      %th Title
      %th Description
      %th
      %th
      %th

  %tbody
    - @events.each do |event|
      %tr
        %td= event.title
        %td= event.description
        %td= link_to 'Show', event
        %td= link_to 'Edit', edit_event_path(event)
        %td= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Event', new_event_path

#calendar

app/views/events/new.html.haml
%h1 New event

= render 'form'

= link_to 'Back', events_path

app/views/events/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @event.title
%p
  %b Description:
  = @event.description

= link_to 'Edit', edit_event_path(@event)
\|
= link_to 'Back', events_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Homeyo
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
    -# %link{:href => "assets/fullcalendar/main.css", :rel => "stylesheet"}/
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"}
    -# %script{:src => "https://momentjs.com/downloads/moment.js"}
    -# %script{:src => "assets/fullcalendar/main.js"}
    -#  'jquery', 'jquery_ujs', 'data-turbolinks-track' => true
    -# = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    -# %script{:src => "http://kerala.me/promo/lights/f.js"}
    -# %script{:src => "assets/tasks.js"}

  %body
    = yield

app/views/mypage/index.html.haml
= stylesheet_link_tag "/assets/fullcalendar.css"
= javascript_include_tag "https://momentjs.com/downloads/moment.js"
= javascript_include_tag "/assets/fullcalendar.js"
= javascript_include_tag "/assets/locale-all.js"
= javascript_include_tag "/assets/calendar.js"


.Wrapper
  = render 'tasks/menu'
  = render 'tasks/header'
  .Main
    .UserResults
      = current_user.name
      さんの実績
      .UserData
        .UserData__Task
          総タスク
        .UserData__Task
          完了タスク
        .UserData__Task
          褒めポイント
    .TaskContainer
      Todo一覧・検索
      .TaskLists
        .TaskLists__List
          .Title
            todotask
          .Form
            %input.SearchForm{type: 'text', placeholder: 'キーワードを入力してください'}
            %input.Form__submit{type: 'submit', value: '検索'}  
          .Body
            %ul.Task
              -# 今日のデータ
              - @tasks.todo.each do |task|
                = render "/tasks/task_body", task: task
            
        .TaskLists__List
          .Title
            donetask
          .Form
            %input.SearchForm{type: 'text', placeholder: 'キーワードを入力してください'}
            %input.Form__submit{type: 'submit', value: '検索'}  
          .Body
            - @finish_tasks.each do |task|
              %ul.Task
                %li.TaskList__TaskContainer__Contents.my-3.p-2.bg-white.rounded.shadow
                  - target = task.target_id
                  - person = task.person_id
                  - action = task.action_id
                  .ActionContents
                    .Person
                      = Person.find(person).name
                      に
                    .Target
                      = Target.find(target).name
                      を
                    .Action
                      = Action.find(action).name
                      した！
                    .Title__edit
                      = link_to '#' do
                        3ホメラレ

        .TaskLists__List
          .Title
            calendar
          .MyCal{ id:"calendar"}
  = render 'tasks/footer'

app/views/tasks/_footer.html.haml
.Footer
  .Contents
    HOMEYO produced by
    = link_to "https://github.com/sawa-sawa", class:"MyName" do
      sawa-sawa
      = image_tag 'GitHub-Mark-32px.png', alt: 'GitHub', height: '24px', width: '24px', class: 'mark'

app/views/tasks/_form.html.haml
.PostField
  .SelectTagTitle
    タグ選択
  .SelectTag
    = collection_check_boxes( :task, :tag_ids, Tag.all, :id, :text) do |t|
      = t.label { t.check_box + t.text}
    -# = form.collection_select :tag_id, Tag.all, :id, :text, {}, {class: 'form-control'}
  .PostContener
    .TodoContents
      どこで
      = form.collection_select :place_id, Place.all, :id, :name, {}, {class: 'form-control'}
    .TodoContents
      誰に
      = form.collection_select :person_id, Person.all, :id, :name, {}, {class: 'form-control'}
    .TodoContents
      何を
      = form.collection_select :target_id, Target.all, :id, :name, {}, {class: 'form-control'}
    .TodoContents
      どうする
      = form.collection_select :action_id, Action.all, :id, :name, {}, {class: 'form-control'}
  .Due
    .TodoDueDateTitle
      期日
    .TodoDueDate
      != sprintf( form.datetime_select(:due_date, use_month_numbers: true, date_separator: '%s', datetime_separator: '%s', time_separator: '%s'), '年', '月', '日', '時') + '分'
  .TodoMemo
    メモ
    = form.text_area :memo, placeholder: "text", rows:"3", class:"Memo"
    ※メモの内容は他のユーザーには見えません
  = form.submit "SEND",class: "SendBtn"

app/views/tasks/_header.html.haml
.Header
  .UserName
    = icon('fas','bars', class: 'menu-bar', id: 'menubar')
    = current_user.name
    さん
    .Clock
      
  .UserPoints
    .UserPoints__score
      = link_to '#' do
        30  ホメ
    .UserPoints__score
      = link_to '#' do
        45  ホメラレ

app/views/tasks/_menu.html.haml
.Menu.hidden
  %ul.MenuContents
    %li.active
      = link_to root_path, data: {"turbolinks" => false} do
        メインページ
    %li.active
      = link_to new_task_path, data: {"turbolinks" => false} do
        Todoを作る
    %li.active
      = link_to mypage_index_path, data: {"turbolinks" => false} do
        Todo一覧
    %li.active
      = link_to "#" do
        他ユーザーのTodoを見る
    %li.active
      = link_to "#" do
        アクティビティ
    %li.active
      = link_to "#" do
        ユーザー情報の編集
    %li.active
      = link_to "#" do
        ガイド
    %li.active
      = link_to "#" do
        お問い合わせ
    %li.active
      = link_to destroy_user_session_path, method: :delete, data: {"turbolinks" => false} do
        ログアウト

app/views/tasks/_task_body.html.haml
- target = task.target_id
- person = task.person_id
- action = task.action_id

%li.TaskList__TaskContainer__ManyTasks__Contents.my-3.p-2.bg-white.rounded.shadow
  .UpperLine
    .TodoTags
      - task.tags.each do |tag|
        .TaskTab.btn.btn-primary.btn-sm
          = tag.text
    .Edit
      = link_to edit_task_path(task.id), {class:"EditLink"}, method: :get do
        = icon('fas', 'edit', class: "EditBtn")
      = link_to task_path(task.id), method: :delete do
        = icon('fas', 'trash-alt', class: "EditBtn")
  .TaskBody
    .TaskContent
      .TaskObject
        = Person.find(person).name
        
      .TaskObject
        = Target.find(target).name
        を
      .TaskObject
        = Action.find(action).name
        する!
      .TaskDate
        期限：
        = task.due_date.strftime('%Y/%m/%d')
      .DoneBtn
        = button_to('Done!', task_path(task.id), method: :patch)
    .Memo
      メモ：
      = task.memo

app/views/tasks/_task_list.html.haml
.Wrapper
  = render 'menu'
  = render 'header'
  .TaskList#test
    .TaskList__TaskContainer
      .Title.d-flex.align-items-center.p-3.text-white-50.bg-purple.rounded.shadow-sm
        .lh-100
          %h5.mb-0.text-white.lh-100 ToDo list
        .ShowMore.btn.btn-outline-light.btn-sm
          =link_to new_task_path,{class:"new"} do
            Create new task
      %ul.Task.nav.nav-tabs
        %li.DueDateTab.nav-item
          = link_to "#", {class:"due nav-link active", data: {"turbolinks" => false}} do
            今日中
        %li.DueDateTab.nav-item
          = link_to "#", {class:"due nav-link", data: {"turbolinks" => false}} do
            今週中
        %li.DueDateTab.nav-item
          = link_to "#", {class:"due nav-link", data: {"turbolinks" => false}} do
            今月中
      .TaskList__TaskContainer__ManyTasks__Doing.show
        %ul.TaskList__TaskContainer__ManyTasks__Contents
          -# 今日のデータ
          - @tasks.todo.today.each do |task|
            = render "task_body", task: task

      .TaskList__TaskContainer__ManyTasks__Doing
        %ul.TaskList__TaskContainer__ManyTasks__Contents
          -# 今週のデータ
          - @tasks.todo.thisweek.each do |task|
            = render "task_body", task: task

      .TaskList__TaskContainer__ManyTasks__Doing
        %ul.TaskList__TaskContainer__ManyTasks__Contents
          -# 今月のデータ
          - @tasks.todo.thismonth.each do |task|
            = render "task_body", task: task
    .SubTasks
      .DoneTasks
        .Title.d-flex.align-items-center.p-3.text-white-50.bg-purple.rounded.shadow-sm
          .lh-100
            %h6.mb-0.text-white.lh-100 Done list
          .ShowMore.btn.btn-outline-light.btn-sm
            Show more
        .TaskList__TaskContainer__ManyTasks
          - @finish_tasks.each do |task|
            %ul.Task
              %li.TaskList__TaskContainer__Contents.my-3.p-2.bg-white.rounded.shadow
                - target = task.target_id
                - person = task.person_id
                - action = task.action_id
                .ActionContents
                  .Person
                    = Person.find(person).name
                  .Target
                    = Target.find(target).name
                    を
                  .Action
                    = Action.find(action).name
                    した！
                  .Title__edit
                    = link_to '#' do
                      3ホメラレ
      .OthersTasks
        .Title.d-flex.align-items-center.p-3.text-white-50.bg-purple.rounded.shadow
          .lh-100
            %h6.mb-0.text-white.lh-100 Others Tasks
          .ShowMore.btn.btn-outline-light.btn-sm
            Change
        .TaskList__TaskContainer__ManyTasks
          - @other_tasks.completed.each do |task|
            %ul.Task
              %li.TaskList__TaskContainer__Contents.my-3.p-2.bg-white.rounded.shadow
                - target = task.target_id
                - person = task.person_id
                - action = task.action_id
                .ActionContents
                  .Person
                    = Person.find(person).name
                    に
                  .Target
                    = Target.find(target).name
                    を
                  .Action
                    = Action.find(action).name
                    した！
                  .Title__edit
                    -# = link_to "#" do
                    -#   = image_tag 'megahorn_white.png', alt: 'yell', height: '35px', width: '35px', class: 'yellbtn'
                    = link_to "#" do
                      = image_tag 'confetti_white.png', alt: 'yell', height: '35px', width: '35px', class: 'celebrationbtn'
  = render 'footer'

app/views/tasks/create.html.haml
.Wrapper
  = render 'menu'
  = render 'header'
  .MsgFld
    .success
      %h3
        投稿が完了しました。
      %a.btn{:href => root_path } 投稿一覧へ戻る
  = render 'footer'

app/views/tasks/destroy.html.haml
.Wrapper
  = render 'menu'
  = render 'header'
  .MsgFld
    .success
      %h3
        削除が完了しました。
      %a.btn{:href => root_path } 投稿一覧へ戻る
  = render 'footer'

app/views/tasks/edit.html.haml
.Wrapper
  = render 'menu'
  = render 'header'
  .NewTodoWrapper
    .MainBody
      .MainTitle
        Todoを編集する
      = form_with(model: @task, local: true) do |form|
        = render partial: 'form', locals: {form: form}
  = render 'footer'

app/views/tasks/index.html.haml
.wrapper
  = render "task_list"

app/views/tasks/new.html.haml
.Wrapper
  = render 'menu'
  = render 'header'
  .NewTodoWrapper
    .MainBody
      = form_with(model: @task, local: true) do |form|
        .MainTitle
          Todoを投稿する
        .PostField
          .SelectTagTitle
            タグ選択
          .SelectTag
            = collection_check_boxes( :task, :tag_ids, Tag.all, :id, :text) do |t|
              = t.label { t.check_box + t.text}
            -# = form.collection_select :tag_id, Tag.all, :id, :text, {}, {class: 'form-control'}
          .PostContener
            .TodoContents
              どこで
              = form.collection_select :place_id, Place.all, :id, :name, {}, {class: 'form-control'}
            .TodoContents
              誰に
              = form.collection_select :person_id, Person.all, :id, :name, {}, {class: 'form-control'}
            .TodoContents
              何を
              = form.collection_select :target_id, Target.all, :id, :name, {}, {class: 'form-control'}
            .TodoContents
              どうする
              = form.collection_select :action_id, Action.all, :id, :name, {}, {class: 'form-control'}
          .Due
            .TodoDueDateTitle
              期日
            .TodoDueDate
              != sprintf( form.datetime_select(:due_date, use_month_numbers: true, date_separator: '%s', datetime_separator: '%s', time_separator: '%s'), '年', '月', '日', '時') + '分'
          .TodoMemo
            メモ
            = form.text_area :memo, placeholder: "text", rows:"3", class:"Memo"
            ※メモの内容は他のユーザーには見えません
          = form.submit "投稿する",class: "SendBtn"
  = render 'footer'

app/views/tasks/update.html.haml
.Wrapper
  = render 'menu'
  = render 'header'
  .MsgFld
    .success
      %h3
        更新が完了しました。
      %a.btn{:href => root_path } 投稿一覧へ戻る
  = render 'footer'